# base URLs for services
# should end in '/'
development:
    fcrepo:
        fcrepo_url: https://fcrepolocal/fcrepo/rest/
        solr_url: http://solrlocal:8983/solr/fedora4/
        image_url: https://iiiflocal/images/
        manifest_url: http://localhost:3000/manifests/
    fedora2:
        fedora2_url: https://fedoradev.lib.umd.edu/
        solr_url: https://solrdev.lib.umd.edu/solr/fedora/
        fcrepo_solr_url: https://solrdev.lib.umd.edu/solr/fedora4/
        image_url: https://iiifdev.lib.umd.edu/images/
        manifest_url: http://localhost:3000/manifests/
vagrant:
    fcrepo:
        fcrepo_url: https://fcrepolocal/fcrepo/rest/
        solr_url: http://solrlocal:8983/solr/fedora4/
        image_url: https://iiiflocal/images/
        manifest_url: https://iiiflocal/manifests/
    fedora2:
        fedora2_url: https://fedoradev.lib.umd.edu/
        solr_url: https://solrdev.lib.umd.edu/solr/fedora/
        fcrepo_solr_url: https://solrdev.lib.umd.edu/solr/fedora4/
        image_url: https://iiifdev.lib.umd.edu/images/
        manifest_url: http://iiiflocal/manifests/
production:
    fcrepo:
        fcrepo_url: <%= ENV['FCREPO_URL'] %>
        solr_url: <%= ENV['SOLR_URL'] %>
        image_url: <%= ENV['IIIF_IMAGE_URL'] %>
        manifest_url: <%= ENV['IIIF_MANIFEST_URL'] %>
    fedora2:
        fedora2_url: <%= ENV['FEDORA2_URL'] %>
        solr_url: <%= ENV['FEDORA2_SOLR_URL'] %>
        fcrepo_solr_url: <%= ENV['FCREPO_SOLR_URL'] %>
        image_url: <%= ENV['IIIF_IMAGE_URL'] %>
        manifest_url: <%= ENV['IIIF_MANIFEST_URL'] %>
